version: '3.4'

services:
  identityservice1.api:
    container_name: identity_service
    image: ${DOCKER_REGISTRY-}identityserviceapi
    build:
      context: .
      dockerfile: src/Services/IdentityService/IdentityService.Api/Dockerfile
  webapigateway1:
    container_name: webapigateway
    image: ${DOCKER_REGISTRY-}webapigateway
    build:
      context: .
      dockerfile: src/ApiGateways/WebApiGateway/Web.ApiGateway/Dockerfile
   
  consul_service:
    container_name: consul
    image: consul