version: '3.4'

services:
  identity.api:
    container_name: c_identity
    image: ${DOCKER_REGISTRY-}identityapi
    build:
      context: .
      dockerfile: src/Services/IdentityService/IdentityService.Api/Dockerfile
  webapigateway.api:
    container_name: apigateway
    image: ${DOCKER_REGISTRY-}apigateway
    build:
      context: .
      dockerfile: src/ApiGateways/WebApiGateway/Web.ApiGateway/Dockerfile
   
  consul_service:
    container_name: consul
    image: consul

  redis_service:
    container_name: redis
    image: redis

  rabbitmq_service:
    container_name: rabbitmq
    image: rabbitmq:3-management