version: '3.4'

services:
  identityservice:
    container_name: identity_service
    image: ${DOCKER_REGISTRY-}identityserviceapi
    build:
      context: .
      dockerfile: src/Services/IdentityService/IdentityService.Api/Dockerfile
  webapigateway:
    container_name: webapigateway
    image: ${DOCKER_REGISTRY-}webapigateway
    build:
      context: .
      dockerfile: src/ApiGateways/WebApiGateway/Web.ApiGateway/Dockerfile
   
  consul_service:
    container_name: consul
    image: consul

  rabbitmq_service:
    container_name: rabbitmq
    image: rabbitmq:3-management