version: '3.4'

services:

  webapigateway.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5011
    ports:
      - "5011:5011"
    networks:
      - apigateway_network
      - backendservice_network

  identity.api:
    expose:
      - "8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5001
      - ConsulConfig__Address=http://consul_service:8500
      - ConsulConfig__ServiceAddress=http://c_identity:5001
      - ConsulConfig__ServiceName=IdentityService
      - ConsulConfig__ServiceId=IdentityService
    ports:
      - "5001:5001"
    networks: 
      - apigateway_network
      - backendservice_network
    depends_on: 
      - webapigateway.api
    external_links: 
      - consul_service

  consul_service:
    ports:
      - 8500:8500
      - 8600:8600/tcp
      - 8600:8600/udp
    networks:
      - apigateway_network
      - backendservice_network


  rabbitmq_service:
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitmq:/var/lib/rabbitmq
    networks:
      - backendservice_network
      - apigateway_network

  redis_service:
    ports:
      - 6379:6379
    volumes:
      - /opt/app_data/redis/:/data
    networks:
      - backendservice_network


networks:
  apigateway_network:
    driver: bridge
    external: true
  backendservice_network:
    driver: bridge
    external: true



volumes:
  rabbitmq: