version: '3.4'

services:
  identity.api:
    container_name: c_identity
    image: ${DOCKER_REGISTRY-}identityapi
    build:
      context: .
      dockerfile: src/Services/IdentityService/IdentityService.Api/Dockerfile
  webapigateway.api:
    container_name: apigateway
    image: ${DOCKER_REGISTRY-}apigateway
    build:
      context: .
      dockerfile: src/ApiGateways/WebApiGateway/Web.ApiGateway/Dockerfile

  order.api:
    container_name: c_orderapi
    image: ${DOCKER_REGISTRY-}orderapi
    build:
      context: .
      dockerfile: src/Services/OrderService/OrderService.Api/Dockerfile
   

  s_sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: c_sqlserver

  consul_service:
    container_name: consul
    image: hashicorp/consul:1.15

  redis_service:
    container_name: redis
    image: redis
    
  rabbitmq_service:
    container_name: rabbitmq
    image: rabbitmq:3-management